# $schema: https://www.schemastore.org/github-workflow.json
name: build-java-container-image

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
        description: The name of the image.

jobs:
  maven-deploy:
    permissions:
      contents: 'read'
      id-token: 'write' # Fetch OIDC Token for GCP Auth
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          distribution: temurin
          java-version: 25
      - uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3
        with:
          workload_identity_provider: projects/401363556022/locations/global/workloadIdentityPools/github/providers/github-oidc
          service_account: automation@automation-220928.iam.gserviceaccount.com
      - run: gcloud auth configure-docker europe-north1-docker.pkg.dev
      - run: >
          mvn deploy
          --no-transfer-progress
          --define image.repository=${{ inputs.image }}
          --define image.tag=${GITHUB_SHA:-latest}
          --define pact.verifier.publishResults=true
          --define pact.broker.url=https://pact.harmelodic.com
          --define pact.broker.username=pact-broker-user
          --define pact.broker.password=${{ secrets.PACT_BROKER_PASSWORD }}
        # pact.broker.* used for publishing Consumer PACTs
        # pact.verifier.publishResults is for publishing Provider test results
        env:
          PACTBROKER_AUTH_USERNAME: pact-broker-user # For publishing Provider results
          PACTBROKER_AUTH_PASSWORD: ${{ secrets.PACT_BROKER_PASSWORD }} # For publishing Provider results
