# $schema: https://www.schemastore.org/github-workflow.json
name: build-go-container-image

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
        description: The name of the image.

jobs:
  docker-build:
    permissions:
      contents: 'read'
      id-token: 'write' # Fetch OIDC Token for GCP Auth
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6
        with:
          go-version-file: go.mod
      # Install golangci-lint (golangci-lint runs during the `make lint`... but also runs as part of the action)
      # (bit wasteful, but it's fast and does caching - so running linting twice is a fair trade-off (for now))
      - uses: golangci/golangci-lint-action@0a35821d5c230e903fcfe077583637dea1b27b47 # v9
        with:
          version: latest
      - run: make
      - run: docker build -t "${{ inputs.image }}:$GITHUB_SHA" .
      - uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3
        with:
          workload_identity_provider: projects/401363556022/locations/global/workloadIdentityPools/github/providers/github-oidc
          service_account: automation@automation-220928.iam.gserviceaccount.com
      - run: gcloud auth configure-docker europe-north1-docker.pkg.dev
      - run: docker push "${{ inputs.image }}:$GITHUB_SHA"
      - run: docker tag "${{ inputs.image }}:$GITHUB_SHA" "${{ inputs.image }}:latest"
      - run: docker push "${{ inputs.image }}:latest"
