# $schema: https://www.schemastore.org/github-workflow.json
name: main

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  verify-workflows:
    uses: ./.github/workflows/verify-github-workflows.yaml
  verify-workflows-with-local:
    uses: ./.github/workflows/verify-github-workflows.yaml
    with:
      use-local-yamllint-config: true
  yamllint-config:
    permissions:
      contents: 'read'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3  # v6
      - run: yamllint .yamllint.yaml
