# $schema: https://www.schemastore.org/github-workflow.json
name: main

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  verify-workflows:
    uses: ./.github/workflows/verify-github-workflows.yaml
  verify-workflows-with-local:
    uses: ./.github/workflows/verify-github-workflows.yaml
    with:
      use-local-yamllint-config: true
  yamllint-config:
    permissions:
      contents: 'read'
    runs-on: ubuntu-latest # yamllint already installed in `ubuntu-latest` runner image.
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6
      - run: yamllint .yamllint.yaml
