# $schema: https://www.schemastore.org/github-workflow.json
name: pull-request

on:
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  verify-workflows:
    uses: ./.github/workflows/verify-github-workflows.yaml
  verify-workflows-with-local:
    uses: ./.github/workflows/verify-github-workflows.yaml
    with:
      use-local-yamllint-config: true
  yamllint-config:
    permissions:
      contents: 'read'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd  # v5
      - run: yamllint .yamllint.yaml
