# $schema: https://www.schemastore.org/github-workflow.json
name: release-mkdocs

on:
  workflow_call:

jobs:
  mkdocs-gh-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6
        with:
          python-version-file: .python-version
      - run: pip install -r requirements.txt
      - run: mkdocs build # MkDocs with strict mode => build fails on broken links, etc.
      - run: mkdocs gh-deploy --force # Deploy as GitHub Pages
