# $schema: https://www.schemastore.org/github-workflow.json
name: release-mkdocs

on:
  workflow_call:

jobs:
  mkdocs-gh-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6
        with:
          python-version-file: .python-version
      - run: pip install -r requirements.txt
      - run: mkdocs build # MkDocs with strict mode => build fails on broken links, etc.
      - run: mkdocs gh-deploy --force # Deploy as GitHub Pages
