# $schema: https://www.schemastore.org/github-workflow.json
name: verify-mkdocs

on:
  workflow_call:
    inputs:
      use-local-yamllint-config:
        required: false
        type: boolean
        default: false
        description: Whether to use the yamllint config already found in the repo.

jobs:
  yamllint:
    permissions:
      contents: 'read'
    runs-on: ubuntu-latest # yamllint already installed in `ubuntu-latest` runner image.
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6
      - run: ${{ inputs.use-local-yamllint-config }} || wget https://raw.githubusercontent.com/Harmelodic/workflows/refs/heads/main/.yamllint.yaml --output-document=.yamllint.yaml
      - run: yamllint docs/
      - run: yamllint mkdocs.yaml
  mkdocs-build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version-file: .python-version
      - run: pip install -r requirements.txt
      - run: mkdocs build # Build in strict mode will validate docs.
