# $schema: https://www.schemastore.org/github-workflow.json
name: verify-go-project

on:
  workflow_call:

jobs:
  make:
    permissions:
      contents: 'read'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6
        with:
          go-version-file: .go-version
      # Install golangci-lint (golangci-lint runs during the `make lint`... but also runs as part of the action)
      # (bit wasteful, but it's fast and does caching - so running linting twice is a fair trade-off (for now))
      - uses: golangci/golangci-lint-action@e7fa5ac41e1cf5b7d48e45e42232ce7ada589601 # v9
        with:
          version: latest
      - run: make
