# $schema: https://www.schemastore.org/github-workflow.json
name: verify-github-workflow

on:
  workflow_call:
    inputs:
      use-local-yamllint-config:
        required: false
        type: boolean
        default: false
        description: Whether to use the yamllint config already found in the repo.

jobs:
  yamllint:
    permissions:
      contents: 'read'
    runs-on: ubuntu-latest # yamllint already installed in `ubuntu-latest` runner image.
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6
      - run: ${{ inputs.use-local-yamllint-config }} || wget https://raw.githubusercontent.com/Harmelodic/workflows/refs/heads/main/.yamllint.yaml --output-document=.yamllint.yaml
      - run: yamllint .github/workflows
  schema-validation:
    permissions:
      contents: 'read'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6
      - run: npm install -g ajv-cli
      - run: wget https://www.schemastore.org/github-workflow.json
      - run: find .github/workflows/*.yaml | xargs -I {} ajv --strict=false -s github-workflow.json -d {}
