# $schema: https://www.schemastore.org/github-workflow.json
name: verify-terraform

on:
  workflow_call:
    inputs:
      directory:
        required: true
        type: string
        description: Path to directory that contains the directory.
      use-local-tflint-config:
        required: false
        type: boolean
        default: false
        description: Whether to use the .tflint.hcl config already found in the repo.

jobs:
  tflint:
    permissions:
      contents: 'read'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
      - uses: terraform-linters/setup-tflint@4cb9feea73331a35b422df102992a03a44a3bb33 # v6
      - run: ${{ inputs.use-local-tflint-config }} || wget https://raw.githubusercontent.com/Harmelodic/workflows/refs/heads/main/.tflint.hcl --output-document=.tflint.hcl
      - run: tflint --init
      - run: tflint --chdir=${{ inputs.directory }}
  checkov:
    permissions:
      contents: 'read'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6
        with:
          python-version: "3.14"
      - run: pip install checkov
      - run: checkov --directory ${{ inputs.directory }}
  terraform-fmt:
    permissions:
      contents: 'read'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3
      - run: terraform -chdir=${{ inputs.directory }} fmt -recursive && git diff --exit-code
  terraform-validate:
    permissions:
      contents: 'read'
      id-token: 'write' # Fetch OIDC Token for GCP Auth
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3
      - uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3
        with:
          workload_identity_provider: projects/401363556022/locations/global/workloadIdentityPools/github/providers/github-oidc
          service_account: terraform-verifier@automation-220928.iam.gserviceaccount.com
      - run: terraform -chdir=${{ inputs.directory }} init -upgrade
      - run: terraform -chdir=${{ inputs.directory }} validate
